# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOb',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_content', models.TextField()),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOb',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOb',
            fields=[
                ('userob_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_eduName', models.CharField(blank=True, max_length=100, null=True)),
                ('user_compName', models.CharField(blank=True, max_length=100, null=True)),
                ('user_dateTime', models.DateTimeField(auto_now_add=True)),
                ('user_eduClass', models.IntegerField(default=0)),
                ('user_adminAbout', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionob',
            name='question_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelv1.UserOb'),
        ),
        migrations.AddField(
            model_name='answerob',
            name='answer_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelv1.QuestionOb'),
        ),
        migrations.AddField(
            model_name='answerob',
            name='answer_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelv1.UserOb'),
        ),
    ]
